Repository TIGNUM/pdf-generation-actions-web-component, pull requests merged in 2021-08, with the labels that each got.

#9 feat: add option of positioning
  index.js
Labels: size/XS

#10 feat: add z-index to the btns
  index.js
Labels: size/XS

#11 change: update the readme
  README.md
Labels: size/M

#14 Feature/emit events to component from dom
  README.md
  demo/index.html
  export/pdf-component.js
  index.js
  test/actionspdf.test.html
Labels: size/L

#16 refactor: remove the css and update the readme after remove the btns form the component
  README.md
  export/pdf-component.js
Labels: size/M
