Repository TIGNUM/pdf-generation-actions-web-component, pull requests merged in 2021-12, with the labels that each got.

#26 feature/WEBDEV-2380-pdf-generation_refactor_LIT_component_to_plain_custom_element
  .eslintignore
  .eslintrc.js
  README.md
  demo/index.html
  export/pdf-component.js
  package-lock.json
  package.json
Labels: size/L

#24 chore: add exported folder to the npmignore file
  .npmignore
Labels: size/XS

#28 fix: fix doble render first time colled
  export/pdf-component.js
Labels: size/S
