Repository TIGNUM/pdf-generation-actions-web-component, pull requests merged in 2021-06, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: size/S

#3 Feature/tests web component
  .github/workflows/pr-checks.yml
  .github/workflows/release-package.yml
  .npmignore
  README.md
  babel.config.json
  demo/index.html
  index.js
  package.json
  test/actionspdf.test.html
  test/test.html
  webpack.config.js
Labels: size/L

#6 feat: add more possibilities for add styles to buttons
  demo/index.html
  index.js
Labels: size/M
